In [1]:
#zip function use

l1 = [1,2,3,4]
l2 = [5,6,7,8]

list(zip(l1,l2))

[(1, 5), (2, 6), (3, 7), (4, 8)]

In [2]:
import numpy as np
import time

In [3]:
# using python list

size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()
print(add[0:10])

print(end - start)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.11656498908996582


In [4]:
# NumPy 

size = 1_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.014249563217163086


In [5]:
np.array([1,3,7,9,9])

array([1, 3, 7, 9, 9])

In [6]:
arr = np.array([[1,5,9,8] , [6,2,8,1]])
print(arr)

[[1 5 9 8]
 [6 2 8 1]]


In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(2, 4)

In [9]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [10]:
size = 1_000_000

l1 = list(range(size))

start = time.time()
list_square = [x ** 2 for x in l1]
end = time.time()

print(end - start)

0.10035848617553711


In [11]:
size = 1_000_000

l1  = np.array(list(range(size)))

start = time.time()
numpy_square = l1 ** 2
end = time.time()

print(end - start)

0.0036537647247314453
