In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])           # 1D array
arr2 = np.array([[1,2,3],[4,5,6]])     # 2D array

print(arr1)
print(f"\n{arr2}")

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]


In [3]:
type(arr2)

numpy.ndarray

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [6]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
myArray = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
myArray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [12]:
myArray.shape

(4, 3)

In [13]:
myArray.size

12

In [14]:
myArray.ndim     # use to know the dimention like , 2D or 3D etc...

2

In [15]:
myArray.dtype

dtype('int64')

In [16]:
myArray = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]] , dtype='float32')   #Explicit type
myArray

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [17]:
myArray.dtype

dtype('float32')

In [18]:
d = myArray.astype('float64')

In [19]:
d.dtype

dtype('float64')

In [20]:
myArray.dtype

dtype('float32')

In [21]:
myArray = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
reshape = myArray.reshape(3,4)

In [22]:
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [23]:
myArray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [24]:
myArray.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])

In [25]:
myArray.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])