In [1]:
import numpy as np

In [2]:
myArray = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [3]:
myArray


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
flat = myArray.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [6]:
flat[3:7]

array([4, 5, 6, 7])

In [7]:
flat[:6]        #same as [0:6]

array([1, 2, 3, 4, 5, 6])

In [8]:
flat[6:]

array([ 7,  8,  9, 11, 12, 13])

# Slicing in array

In [9]:
g = flat[3:10]

In [10]:
g

array([ 4,  5,  6,  7,  8,  9, 11])

In [11]:
g[0] = 2340

## Slicing returns a view, not a copy! Changes affect the original array.**

In [12]:
g

array([2340,    5,    6,    7,    8,    9,   11])

In [13]:
flat

array([   1,    2,    3, 2340,    5,    6,    7,    8,    9,   11,   12,
         13])

### If we want to make the separated copy of sliced part 

In [14]:
c = flat[2:7].copy()

In [15]:
c

array([   3, 2340,    5,    6,    7])

In [16]:
c[1] = 45

In [17]:
c

array([ 3, 45,  5,  6,  7])

In [18]:
flat

array([   1,    2,    3, 2340,    5,    6,    7,    8,    9,   11,   12,
         13])

### fancy indexing

In [19]:
arr = np.array([23,6,55,5,623,7,424,45,2,34,33,2])

In [20]:
indices_of = arr[[2,5,8]]

In [21]:
print(indices_of)

[55  7  2]


In [22]:
arr[arr > 33]

array([ 55, 623, 424,  45,  34])

### Exercise

In [23]:
newArray = np.array([[1,2,3],[7,8,9],[0,5,4]])

In [24]:
newArray.shape

(3, 3)

In [25]:
float_array = np.array([1.1 , 2.2 ,3.3],dtype = 'int64')

In [26]:
float_array.dtype

dtype('int64')

In [27]:
float_array

array([1, 2, 3])

In [28]:
arr_number = np.array([1,2,3,4,5,6])

In [29]:
even_number = arr_number[[1,3,5]]

In [30]:
even_number

array([2, 4, 6])

In [31]:
one_dimention_array = np.array([1,2,3,4,5,6,7,8,9])

In [32]:
one_dimention_array.ndim

1

In [33]:
reshape = one_dimention_array.reshape(3,3)

In [34]:
reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
boolean_masking = np.array([23,24,42,32,4,564,5,7,56,453,24,454,32,44,545,34,34,45,65,57,78,79,78,65,3,4,90])

In [36]:
greater = boolean_masking[boolean_masking > 50]

In [37]:
greater

array([564,  56, 453, 454, 545,  65,  57,  78,  79,  78,  65,  90])