# Axis

#### 1D array → 1 axis (axis 0)
#### 2D array → 2 axes (axis 0 = rows, axis 1 = columns)
#### 3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [1]:
import numpy as np

In [2]:
myArray = np.array([[1,2,3] ,
                   [4,5,6],
                   [7,8,9]])

In [3]:
myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
myArray[1]

array([4, 5, 6])

In [5]:
myArray[: , 1]

array([2, 5, 8])

In [6]:
print(np.sum(myArray, axis=0))                     # Sum along rows (down each column)
print(np.sum(myArray, axis=1))                     # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


#  Indexing in Multidimensional Arrays

In [7]:
myArray[0][1]

np.int64(2)

In [8]:
myArray[0:2 , 1:3]    # [Rows , column] ,here 0:2 means include the rows from 0 to 2 but not 2 so, 0 and 1

array([[2, 3],
       [5, 6]])

In [9]:
array_3D = np.array([[[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]]]) 


In [10]:
array_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
array_3D.ndim

3

In [12]:
array_3D.shape

(2, 2, 3)

In [13]:
array_3D[1,1,2]     # [sheet , row , column]

np.int64(12)

In [14]:
array_3D[:,0,:]            # if any axis is not defined then select all element

array([[1, 2, 3],
       [7, 8, 9]])

# changing data along axis

In [15]:
myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
myArray[: , 1]

array([2, 5, 8])

In [17]:
myArray[: , 1] = 0     #change data
myArray

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])