In [1]:
import numpy as np

## Looping Over Arrays in Python

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = []

# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)

print(result) 

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


## Vectorized Operation

In [3]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2                          # Vectorized operation
print(result)  

[ 1  4  9 16 25]


## brodcasting with scaler 

In [4]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10                        # Broadcasting: 10 is added to all elements
print(result) 

[11 12 13 14 15]


## brodcasting with two arrays

In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2                       # Element-wise addition
print(result)  

[11 22 33]


## Broadcasting a 2D Array and a 1D Array

In [6]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2                               # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]


## Example

In [7]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
