In [1]:
import numpy as np

In [2]:
myArray = np.array([1,2,3,4,5,6,7,8,9,10])

# highly used mathematical function

In [3]:
np.mean(myArray)      #average

np.float64(5.5)

In [4]:
np.min(myArray)

np.int64(1)

In [5]:
np.max(myArray)

np.int64(10)

In [6]:
np.std(myArray)             #standerd deviation

np.float64(2.8722813232690143)

In [7]:
np.var(myArray)            # varience

np.float64(8.25)

In [8]:
np.sum(myArray)           # Sum

np.int64(55)

In [9]:
np.prod(myArray)          # Product

np.int64(3628800)

In [10]:
np.median(myArray)          # median

np.float64(5.5)

In [11]:
np.percentile(myArray , 50)     # For the 50th percentile

np.float64(5.5)

In [12]:
np.argmin(myArray)          # index of the minimum

np.int64(0)

In [13]:
np.argmax(myArray)          # index of the max

np.int64(9)

In [14]:
temp = np.array([23,45,7,68,34,12,43,54,76,4])
np.corrcoef(myArray , temp)                     # correlation coefficient

array([[1.        , 0.13429684],
       [0.13429684, 1.        ]])

In [15]:
temp = np.array([23,45,7,68,4,12,4,54,76,4])
np.unique(temp)                                    # unique element

array([ 4,  7, 12, 23, 45, 54, 68, 76])

In [16]:
np.diff(temp)                        # n-th differences

array([ 22, -38,  61, -64,   8,  -8,  50,  22, -72])

In [17]:
np.cumsum(myArray)                    # cumulative sum

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [18]:
np.linspace(0,99,10)                # evenly spaced numbers

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [19]:
np.log(myArray)               # natural logarithm

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [20]:
np.exp(myArray)              # Exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])